dataset: NCI109
aug: baseline
model_type: transformer-gnn

gnn_type: gin
gnn_virtual_node: false

graph_pooling: mean

lr: 0.0001

seed: 12344

transformer_norm_input: true

runs: 20
epochs: 100

d_model: 128
dim_feedforward: 256
num_encoder_layers: 4
scheduler: cosine

transformer_dropout: 0.1
gnn_dropout: 0.1
