dataset: ogbg-code2
aug: baseline
model_type: pna-transformer

graph_pooling: cls

batch_size: 16
lr: 0.0001

runs: 1
seed: 12344

transformer_norm_input: true


gnn_emb_dim: 272
scheduler: plateau

gnn_num_layer: 4
epochs: 30
batch_size: 16
weight_decay: 3e-6
gnn_dropout: 0

start-eval: 10
test-freq: 5